# Generated by Django 5.2.7 on 2026-03-23 01:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturi'},
        ),
        migrations.AlterModelOptions(
            name='invoiceline',
            options={'verbose_name': 'Linie factura', 'verbose_name_plural': 'Linii factura'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Adresa client'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client_fiscal_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='CIF client'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_address',
            field=models.CharField(max_length=300, verbose_name='Adresa'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Oras'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Denumire firma'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Scadenta'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numar'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Emisa'), ('paid', 'Achitata'), ('cancelled', 'Anulata')], default='draft', max_length=12),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Pret unitar'),
        ),
    ]
