# Generated by Django 5.2.7 on 2026-04-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_options_alter_invoiceline_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Ciornita'), ('final', 'Emisa'), ('paid', 'Achitata'), ('cancelled', 'Anulata')], default='draft', max_length=12),
        ),
    ]
