# Generated by Django 5.2.7 on 2026-03-04 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Denumire')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descriere')),
                ('icon', models.CharField(default='🔧', max_length=50, verbose_name='Icon (emoji)')),
                ('color', models.CharField(default='#e63946', max_length=20, verbose_name='Culoare hex')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine afișare')),
            ],
            options={
                'verbose_name': 'Categorie Serviciu',
                'verbose_name_plural': 'Categorii Servicii',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Denumire service')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='Descriere')),
                ('address', models.CharField(max_length=300, verbose_name='Adresă')),
                ('city', models.CharField(choices=[('bucuresti', 'București'), ('cluj-napoca', 'Cluj-Napoca'), ('timisoara', 'Timișoara'), ('iasi', 'Iași'), ('brasov', 'Brașov'), ('constanta', 'Constanța'), ('craiova', 'Craiova'), ('galati', 'Galați'), ('ploiesti', 'Ploiești'), ('oradea', 'Oradea'), ('sibiu', 'Sibiu'), ('arad', 'Arad'), ('pitesti', 'Pitești'), ('bacau', 'Bacău'), ('targu-mures', 'Târgu Mureș')], max_length=50, verbose_name='Oraș')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('schedule', models.CharField(default='Lun-Vin: 08:00-18:00', max_length=200, verbose_name='Program lucru')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Recomandat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicecategory', verbose_name='Categorie principală')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_centers', to=settings.AUTH_USER_MODEL, verbose_name='Proprietar cont')),
            ],
            options={
                'verbose_name': 'Service Auto',
                'verbose_name_plural': 'Service-uri Auto',
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Denumire serviciu')),
                ('description', models.TextField(blank=True, verbose_name='Detalii')),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preț de la (RON)')),
                ('price_to', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preț până la (RON)')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durată estimată (min)')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Popular')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceitem_set', to='services.servicecenter', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Serviciu Oferit',
                'verbose_name_plural': 'Servicii Oferite',
                'ordering': ['-is_popular', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 ★'), (2, '2 ★'), (3, '3 ★'), (4, '4 ★'), (5, '5 ★')], verbose_name='Rating')),
                ('title', models.CharField(max_length=200, verbose_name='Titlu recenzie')),
                ('body', models.TextField(verbose_name='Textul recenziei')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True, verbose_name='Aprobată')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilizator')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicecenter', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Recenzie',
                'verbose_name_plural': 'Recenzii',
                'ordering': ['-created_at'],
                'unique_together': {('center', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='services.servicecenter')),
            ],
            options={
                'verbose_name': 'Favorit',
                'verbose_name_plural': 'Favorite',
                'unique_together': {('user', 'center')},
            },
        ),
    ]
