# Generated by ChatGPT on 2026-03-05
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecenter',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Denumire legală (opțional)'),
        ),
        migrations.AddField(
            model_name='servicecenter',
            name='headquarters',
            field=models.CharField(blank=True, max_length=300, verbose_name='Sediu social (opțional)'),
        ),
        migrations.AddField(
            model_name='servicecenter',
            name='fiscal_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cod fiscal / CIF (opțional)'),
        ),
        migrations.AddField(
            model_name='servicecenter',
            name='trade_register_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nr. Registrul Comerțului (opțional)'),
        ),
        migrations.AddField(
            model_name='servicecenter',
            name='legal_document',
            field=models.FileField(blank=True, null=True, upload_to='legal_docs/', verbose_name='Document legal (opțional)'),
        ),
    ]
