# Generated by Django 5.2.12 on 2026-03-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicecenter_card_image_servicecenter_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecenter',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True),
        ),
    ]
