# Generated by Django 5.2.7 on 2026-03-07 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_servicecenter_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicegarage',
            name='close_time',
            field=models.TimeField(default='18:00', verbose_name='Închidere'),
        ),
        migrations.AddField(
            model_name='servicegarage',
            name='open_time',
            field=models.TimeField(default='08:00', verbose_name='Deschidere'),
        ),
        migrations.AddField(
            model_name='servicegarage',
            name='slot_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='Durată slot (minute)'),
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='review_images/', verbose_name='Poză recenzie')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.review')),
            ],
            options={
                'verbose_name': 'Poză recenzie',
                'verbose_name_plural': 'Poze recenzii',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
