# Generated by Django 6.0.3 on 2026-03-09 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_servicegarage_close_time_servicegarage_open_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Nume companie / service')),
                ('contact_person', models.CharField(blank=True, max_length=120, verbose_name='Persoană contact')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email contact')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon contact')),
                ('notes', models.TextField(blank=True, verbose_name='Observații interne')),
                ('is_signed', models.BooleanField(default=False, verbose_name='Contract semnat')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Semnat la')),
                ('access_token', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Token acces')),
                ('access_token_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Token generat la')),
                ('access_link_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Link folosit la')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Creat de')),
                ('linked_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='services.servicecenter', verbose_name='Service creat')),
                ('linked_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Proprietar cont legat')),
            ],
            options={
                'verbose_name': 'Contract service',
                'verbose_name_plural': 'Contracte service',
                'ordering': ['-created_at'],
            },
        ),
    ]
