# Generated by Django 5.2.7 on 2026-03-09 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_servicecontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Nume mecanic')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanics', to='services.servicecenter', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Mecanic service',
                'verbose_name_plural': 'Mecanici service',
                'ordering': ['name'],
            },
        ),
    ]
