# Generated by Django 5.2.7 on 2026-03-17 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_mechanic_garage_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicphoto',
            name='photo_type',
            field=models.CharField(choices=[('before', 'Inainte de reparatie'), ('after', 'Dupa reparatie'), ('during', 'In timpul reparatiei')], default='before', max_length=10, verbose_name='Tip fotografie'),
        ),
        migrations.CreateModel(
            name='ServicePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Denumire piesă')),
                ('part_number', models.CharField(blank=True, max_length=80, verbose_name='Cod piesă')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stoc curent')),
                ('minimum_stock', models.PositiveIntegerField(default=0, verbose_name='Stoc minim')),
                ('unit', models.CharField(default='buc', max_length=20, verbose_name='Unitate')),
                ('shelf', models.CharField(blank=True, max_length=80, verbose_name='Raft / locație')),
                ('notes', models.TextField(blank=True, verbose_name='Observații')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='services.servicecenter', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Piesă service',
                'verbose_name_plural': 'Piese service',
                'ordering': ['name'],
                'unique_together': {('center', 'name', 'part_number')},
            },
        ),
    ]
