# Generated by Django 5.2.7 on 2026-03-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_mechanicphoto_photo_type_servicepart'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepart',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preț achiziție (RON)'),
        ),
        migrations.AddField(
            model_name='servicepart',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preț vânzare (RON)'),
        ),
    ]
