# Generated by Django 5.2.7 on 2026-03-23 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_alter_booking_options_and_more'),
        ('services', '0013_servicepart_extended_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepart',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AddField(
            model_name='servicepart',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pret achizitie'),
        ),
        migrations.AddField(
            model_name='servicepart',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pret vanzare'),
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Creata'), ('approved', 'Aprobata'), ('in_progress', 'In lucru'), ('waiting_parts', 'Asteapta piese'), ('waiting_customer', 'Asteapta confirmare client'), ('completed', 'Finalizata'), ('invoiced', 'Facturata'), ('closed', 'Inchisa')], default='created', max_length=24, verbose_name='Status lucrare')),
                ('diagnostic_summary', models.TextField(blank=True, verbose_name='Diagnostic si observatii tehnice')),
                ('work_performed', models.TextField(blank=True, verbose_name='Operatiuni efectuate')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Note interne')),
                ('customer_notes', models.TextField(blank=True, verbose_name='Note vizibile clientului')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometraj')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Timp estimat (ore)')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Timp real (ore)')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost estimat (RON)')),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost final (RON)')),
                ('next_service_date', models.DateField(blank=True, null=True, verbose_name='Data recomandata pentru urmatoarea revizie')),
                ('next_service_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometraj recomandat pentru urmatoarea revizie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_card', to='bookings.booking', verbose_name='Programare')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_cards', to='services.servicecenter', verbose_name='Service')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_job_cards', to=settings.AUTH_USER_MODEL, verbose_name='Creata de')),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_cards', to='services.servicemechanic', verbose_name='Mecanic alocat')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_job_cards', to=settings.AUTH_USER_MODEL, verbose_name='Actualizata de')),
            ],
            options={
                'verbose_name': 'Fisa lucrare',
                'verbose_name_plural': 'Fise lucrari',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Operatiune')),
                ('description', models.TextField(blank=True, verbose_name='Detalii')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost estimat')),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost final')),
                ('is_visible_to_customer', models.BooleanField(default=True, verbose_name='Vizibila clientului')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='services.jobcard', verbose_name='Fisa lucrare')),
            ],
            options={
                'verbose_name': 'Operatiune lucrare',
                'verbose_name_plural': 'Operatiuni lucrare',
                'ordering': ['position', 'created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='JobPartUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=180, verbose_name='Descriere')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantitate')),
                ('unit_label', models.CharField(blank=True, max_length=20, verbose_name='Unitate')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost achizitie')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pret vanzare')),
                ('status', models.CharField(choices=[('reserved', 'Rezervata'), ('consumed', 'Consumata'), ('returned', 'Returnata')], default='reserved', max_length=12, verbose_name='Status piesa')),
                ('notes', models.CharField(blank=True, max_length=220, verbose_name='Observatii')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_job_part_usages', to=settings.AUTH_USER_MODEL, verbose_name='Adaugata de')),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_usages', to='services.jobcard', verbose_name='Fisa lucrare')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_usages', to='services.servicepart', verbose_name='Piesa din stoc')),
            ],
            options={
                'verbose_name': 'Piesa folosita in lucrare',
                'verbose_name_plural': 'Piese folosite in lucrare',
                'ordering': ['-created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='JobRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Recomandare')),
                ('details', models.TextField(blank=True, verbose_name='Detalii')),
                ('priority', models.CharField(choices=[('low', 'Scazuta'), ('medium', 'Medie'), ('high', 'Ridicata')], default='medium', max_length=10, verbose_name='Prioritate')),
                ('is_visible_to_customer', models.BooleanField(default=True, verbose_name='Vizibila clientului')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Rezolvata')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Rezolvata la')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Recomandata pana la')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='services.jobcard', verbose_name='Fisa lucrare')),
            ],
            options={
                'verbose_name': 'Recomandare tehnica',
                'verbose_name_plural': 'Recomandari tehnice',
                'ordering': ['is_resolved', '-created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAvailabilityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('closed', 'Service inchis'), ('break', 'Pauza'), ('vacation', 'Concediu'), ('maintenance', 'Blocaj operational')], default='closed', max_length=20, verbose_name='Tip blocare')),
                ('title', models.CharField(max_length=160, verbose_name='Titlu')),
                ('notes', models.TextField(blank=True, verbose_name='Observatii')),
                ('starts_at', models.DateTimeField(verbose_name='De la')),
                ('ends_at', models.DateTimeField(verbose_name='Pana la')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to='services.servicecenter', verbose_name='Service')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_availability_blocks', to=settings.AUTH_USER_MODEL, verbose_name='Creat de')),
                ('garage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to='services.servicegarage', verbose_name='Garaj')),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to='services.servicemechanic', verbose_name='Mecanic')),
            ],
            options={
                'verbose_name': 'Bloc disponibilitate',
                'verbose_name_plural': 'Blocari disponibilitate',
                'ordering': ['starts_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Intrare in stoc'), ('out', 'Iesire din stoc'), ('adjustment', 'Ajustare manuala'), ('reserve', 'Rezervare pentru lucrare'), ('release', 'Eliberare / retur')], max_length=20, verbose_name='Tip miscare')),
                ('quantity_delta', models.IntegerField(verbose_name='Delta stoc')),
                ('previous_stock', models.PositiveIntegerField(verbose_name='Stoc anterior')),
                ('new_stock', models.PositiveIntegerField(verbose_name='Stoc nou')),
                ('note', models.CharField(blank=True, max_length=220, verbose_name='Observatii')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Utilizator')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='bookings.booking', verbose_name='Programare')),
                ('job_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='services.jobcard', verbose_name='Fisa lucrare')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='services.servicepart', verbose_name='Piesa')),
            ],
            options={
                'verbose_name': 'Miscare stoc',
                'verbose_name_plural': 'Miscari stoc',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
