# Generated by Django 6.0.3 on 2026-03-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_carexpiryprofile_casco_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(max_length=17, verbose_name='Serie șasiu (VIN)'),
        ),
    ]
