# Generated by Django 5.2.7 on 2026-03-19 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_legalacceptance'),
        ('accounts', '0004_alter_car_vin'),
    ]

    operations = [
    ]
