# Generated by Django 5.2.7 on 2026-05-05 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_oauthaccount'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='oauthaccount',
            new_name='accounts_oa_provide_ff2ef1_idx',
            old_name='accounts_oa_provide_78c1a3_idx',
        ),
    ]
