# Generated by Django 5.2.7 on 2026-03-06 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicecenter_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecenter',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to='service_cards/', verbose_name='Poză card service'),
        ),
        migrations.AddField(
            model_name='servicecenter',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='center_categories', to='services.servicecategory', verbose_name='Categorii disponibile'),
        ),
        migrations.CreateModel(
            name='ServiceGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nume garaj')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicecategory', verbose_name='Categorie')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garages', to='services.servicecenter', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Garaj service',
                'verbose_name_plural': 'Garaje service',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_gallery/', verbose_name='Poză')),
                ('caption', models.CharField(blank=True, max_length=120, verbose_name='Descriere scurtă')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='services.servicecenter', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Poză service',
                'verbose_name_plural': 'Poze service',
                'ordering': ['-created_at'],
            },
        ),
    ]
