# Generated by Django 5.2.7 on 2026-03-04 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nume complet')),
                ('client_phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('car_brand', models.CharField(max_length=100, verbose_name='Marcă')),
                ('car_model', models.CharField(max_length=100, verbose_name='Model')),
                ('car_year', models.PositiveIntegerField(verbose_name='An fabricație')),
                ('car_fuel', models.CharField(choices=[('benzina', 'Benzină'), ('motorina', 'Motorină'), ('hibrid', 'Hibrid'), ('electric', 'Electric'), ('gpl', 'GPL')], max_length=20, verbose_name='Combustibil')),
                ('car_plate', models.CharField(max_length=20, verbose_name='Nr. înmatriculare')),
                ('problem_description', models.TextField(verbose_name='Descriere problemă / serviciu dorit')),
                ('booking_date', models.DateField(verbose_name='Data programării')),
                ('booking_time', models.TimeField(verbose_name='Ora programării')),
                ('status', models.CharField(choices=[('pending', 'În așteptare'), ('confirmed', 'Confirmată'), ('in_progress', 'În lucru'), ('done', 'Finalizată'), ('cancelled', 'Anulată')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Note interne (admin)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.servicecenter', verbose_name='Service')),
                ('service_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.serviceitem', verbose_name='Serviciu ales')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Cont utilizator')),
            ],
            options={
                'verbose_name': 'Programare',
                'verbose_name_plural': 'Programări',
                'ordering': ['-created_at'],
            },
        ),
    ]
