# Generated by Django 5.2.7 on 2026-03-07 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookingnotification'),
        ('services', '0007_servicegarage_close_time_servicegarage_open_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='garage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='services.servicegarage', verbose_name='Garaj'),
        ),
        migrations.CreateModel(
            name='BookingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='booking_attachments/')),
                ('media_kind', models.CharField(choices=[('image', 'Imagine'), ('video', 'Video')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Atașament programare',
                'verbose_name_plural': 'Atașamente programări',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
