# Generated by Django 6.0.3 on 2026-03-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='car_vin',
            field=models.CharField(default='', max_length=17, verbose_name='Serie șasiu (VIN)'),
        ),
    ]
