# Generated by Django 5.2.7 on 2026-03-09 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_car_vin'),
        ('services', '0009_servicemechanic'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='services.servicemechanic', verbose_name='Mecanic alocat'),
        ),
    ]
