# Generated by Django 5.2.7 on 2026-03-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_mechanic'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_description',
            field=models.TextField(blank=True, verbose_name='Descriere suplimentară pentru fișă'),
        ),
        migrations.AddField(
            model_name='booking',
            name='used_services',
            field=models.TextField(blank=True, verbose_name='Servicii / piese folosite'),
        ),
    ]
