# Generated by Django 5.2.7 on 2026-03-17 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_block_end_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='block_end_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='block_end_time',
        ),
    ]
