# Generated by Django 5.2.7 on 2026-03-18 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_reminder_sent_1d'),
        ('services', '0013_servicepart_cost_price_servicepart_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='mechanic',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='used_services',
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Motiv anulare'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Anulat la'),
        ),
        migrations.AddField(
            model_name='bookingattachment',
            name='attachment_stage',
            field=models.CharField(choices=[('before', 'Înainte de reparație'), ('during', 'În timpul reparației'), ('after', 'După reparație')], default='before', max_length=10, verbose_name='Etapă'),
        ),
        migrations.AddField(
            model_name='bookingattachment',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descriere'),
        ),
        migrations.AddField(
            model_name='bookingattachment',
            name='is_visible_to_client',
            field=models.BooleanField(default=True, verbose_name='Vizibil pentru client'),
        ),
        migrations.AddField(
            model_name='bookingattachment',
            name='uploaded_by_role',
            field=models.CharField(choices=[('client', 'Client'), ('mechanic', 'Mecanic'), ('admin', 'Admin')], default='client', max_length=10, verbose_name='Încărcat de'),
        ),
        migrations.CreateModel(
            name='BookingMechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Alocat la')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Mecanic principal')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanics', to='bookings.booking', verbose_name='Programare')),
                ('service_mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_assignments', to='services.servicemechanic', verbose_name='Mecanic')),
            ],
            options={
                'verbose_name': 'Mecanic programare',
                'verbose_name_plural': 'Mecanici programare',
                'ordering': ['-is_primary', 'assigned_at'],
                'unique_together': {('booking', 'service_mechanic')},
            },
        ),
    ]
