# Generated by Django 5.2.7 on 2026-03-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_reminder_sent_1d'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='wants_offer',
            field=models.BooleanField(default=False, verbose_name='Client dorește ofertă înainte de confirmare'),
        ),
    ]
