# Generated by Django 5.2.7 on 2026-03-21 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_booking_wants_offer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='operational_tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Tag-uri operationale'),
        ),
        migrations.CreateModel(
            name='BookingActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('status_changed', 'Status schimbat'), ('offer_updated', 'Oferta actualizata'), ('mechanic_changed', 'Mecanic schimbat'), ('schedule_changed', 'Programare mutata'), ('attachment_added', 'Fisier adaugat'), ('note_updated', 'Nota interna actualizata'), ('tags_updated', 'Tag-uri actualizate'), ('checklist_updated', 'Checklist actualizat')], max_length=40)),
                ('message', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Activity log booking',
                'verbose_name_plural': 'Activity logs booking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=160)),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='bookings.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_booking_checklist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Checklist booking',
                'verbose_name_plural': 'Checklist booking',
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
