# Generated by Django 5.2.7 on 2026-03-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_booking_operational_tags_bookingactivitylog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Programare', 'verbose_name_plural': 'Programari'},
        ),
        migrations.AlterModelOptions(
            name='bookingattachment',
            options={'ordering': ['uploaded_at'], 'verbose_name': 'Atasament programare', 'verbose_name_plural': 'Atasamente programari'},
        ),
        migrations.AlterModelOptions(
            name='bookingnotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notificare programare', 'verbose_name_plural': 'Notificari programari'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='additional_description',
            field=models.TextField(blank=True, verbose_name='Descriere suplimentara pentru fisa'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(verbose_name='Data programarii'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(verbose_name='Ora programarii'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='car_brand',
            field=models.CharField(max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='car_fuel',
            field=models.CharField(choices=[('benzina', 'Benzina'), ('motorina', 'Motorina'), ('hibrid', 'Hibrid'), ('electric', 'Electric'), ('gpl', 'GPL')], max_length=20, verbose_name='Combustibil'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='car_plate',
            field=models.CharField(max_length=20, verbose_name='Nr. inmatriculare'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='car_vin',
            field=models.CharField(default='', max_length=17, verbose_name='Serie sasiu (VIN)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='car_year',
            field=models.PositiveIntegerField(verbose_name='An fabricatie'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Durata blocare garaj (minute)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pret aproximativ (RON)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Note interne'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='problem_description',
            field=models.TextField(verbose_name='Descriere problema / serviciu dorit'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reminder_sent_1d',
            field=models.BooleanField(default=False, verbose_name='Reminder SMS trimis cu o zi inainte'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'In asteptare'), ('quoted', 'Oferta trimisa'), ('confirmed', 'Confirmata'), ('in_progress', 'In lucru'), ('waiting_parts', 'Asteapta piese'), ('done', 'Finalizata'), ('cancelled', 'Anulata')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='wants_offer',
            field=models.BooleanField(default=False, verbose_name='Client doreste oferta inainte de confirmare'),
        ),
        migrations.AlterField(
            model_name='bookingnotification',
            name='kind',
            field=models.CharField(choices=[('booking_new', 'Programare noua'), ('status_update', 'Actualizare status')], max_length=30),
        ),
    ]
