# Generated by Django 5.2.7 on 2026-04-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cerere service', 'verbose_name_plural': 'Cereri service'},
        ),
        migrations.AlterModelOptions(
            name='bookingattachment',
            options={'ordering': ['uploaded_at'], 'verbose_name': 'Atasament cerere/lucrare', 'verbose_name_plural': 'Atasamente cereri/lucrari'},
        ),
        migrations.AlterModelOptions(
            name='bookingnotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notificare cerere', 'verbose_name_plural': 'Notificari cereri'},
        ),
        migrations.AddField(
            model_name='booking',
            name='preferred_date_2',
            field=models.DateField(blank=True, null=True, verbose_name='A doua preferinta - data'),
        ),
        migrations.AddField(
            model_name='booking',
            name='preferred_date_3',
            field=models.DateField(blank=True, null=True, verbose_name='A treia preferinta - data'),
        ),
        migrations.AddField(
            model_name='booking',
            name='preferred_time_2',
            field=models.TimeField(blank=True, null=True, verbose_name='A doua preferinta - ora'),
        ),
        migrations.AddField(
            model_name='booking',
            name='preferred_time_3',
            field=models.TimeField(blank=True, null=True, verbose_name='A treia preferinta - ora'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(verbose_name='Prima preferinta - data'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(verbose_name='Prima preferinta - ora'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Durata estimata (minute)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Cerere trimisa'), ('quoted', 'Propunere trimisa'), ('confirmed', 'Confirmata'), ('in_progress', 'In lucru'), ('waiting_parts', 'Asteapta aprobare client'), ('done', 'Finalizata'), ('cancelled', 'Respinsa')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='bookingnotification',
            name='kind',
            field=models.CharField(choices=[('booking_new', 'Cerere noua'), ('status_update', 'Actualizare status')], max_length=30),
        ),
    ]
