# Generated by Django 5.2.7 on 2026-04-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration_estimate_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Incredere estimare durata'),
        ),
        migrations.AddField(
            model_name='booking',
            name='duration_estimate_source',
            field=models.CharField(blank=True, default='', max_length=24, verbose_name='Sursa estimarii duratei'),
        ),
        migrations.AddField(
            model_name='booking',
            name='estimated_operation_label',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Operatie estimata'),
        ),
        migrations.AddField(
            model_name='booking',
            name='estimated_operation_slug',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Operatie estimata (slug)'),
        ),
    ]
